#!/usr/bin/env sh
# )A( - Andromeda
#
# startApp  wrapper
#
# (c) 2010-2013 Luca Cappelletti <luca.cappelletti@gmail.com>
#
# copyleft GNU/GPL all rights reserved
#
# do not forget now you have .cache/Volatile full private temp folder service
# made by startApp

# SkippyHD specific
# /home/$AppName/.config/skippy-xd/skippy-xd.rc
#

options="$@"

APP_NAME=SkippyXD
APP_RELEASE=GIT02092013
APP_KERNEL=Linux
APP_OS=Debian7
APP_PLATFORM=ia32

APP_BIN=skippy-xd

APP_ROOT=io$APP_NAME$APP_RELEASE-$APP_OS
SANDBOX_HOME=$APP_NAME

export LD_LIBRARY_PATH=/home/$APP_NAME/.App/$APP_ROOT/$APP_KERNEL-$APP_PLATFORM/support:/home/$APP_NAME/.App/$APP_ROOT/$APP_KERNEL-$APP_PLATFORM/lib:$LD_LIBRARY_PATH
export PATH=/home/$APP_NAME/.App/$APP_ROOT/$APP_KERNEL-$APP_PLATFORM/bin:$PATH

cd $HOME

killall $APP_BIN
wait

rm /tmp/skippy-xd-fifo
wait

/home/$APP_NAME/.App/$APP_ROOT/$APP_KERNEL-$APP_PLATFORM/bin/$APP_BIN $options

